updates validatePR with code for validate-pull-request & adds filler echo for validate-branch

diff --git a/.github/workflows/validatePR.yml b/.github/workflows/validatePR.yml
--- a/.github/workflows/validatePR.yml
+++ b/.github/workflows/validatePR.yml
@@ -14,9 +14,36 @@ jobs:
   validate-pull-request:
     runs-on: ubuntu-latest
 
+    steps:
+      - uses: actions/checkout@v4
+      - name: Check Pull Request Draft Status
+        run: |
+          echo "$(date "+%F %H:%M:%S") | Check Pull Request Draft Status | START"
+          if [ ${{ github.event.pull_request.draft }} == true ]; then
+            echo "$(date "+%F %H:%M:%S") | Check Pull Request Draft Status | FAILURE"
+            exit 1;
+          fi
+          echo "$(date "+%F %H:%M:%S") | Check Pull Request Draft Status | END"
+
+      - name: Check Pull Request Description
+        run: |
+          echo "$(date "+%F %H:%M:%S") | Check Pull Request Description | START"
+          if [ -z "${{ github.event.pull_request.body }}" ]; then
+            echo "$(date "+%F %H:%M:%S") | Check Pull Request Description | FAILURE"
+            exit 1;
+          fi
+          echo "$(date "+%F %H:%M:%S") | Check Pull Request Description | END"
+
   validate-branch:
     runs-on: ubuntu-latest
 
+    steps:
+      - uses: actions/checkout@v4
+      - name: Check Branch Integrity
+        run: |
+          echo "$(date "+%F %H:%M:%S") | Check Branch Integrity | START"
+          echo "Branch: ${{ github.event.pull_request.head.ref }}"
+          echo "$(date "+%F %H:%M:%S") | Check Branch Integrity | END"
 
   validate-build:
     runs-on: ubuntu-latest
@@ -29,10 +56,19 @@ jobs:
           node-version: '20'
 
       - name: Install Dependencies
-        run: npm install
+        run: |
+          echo "$(date "+%F %H:%M:%S") | Install Dependencies | START"
+          npm install
+          echo "$(date "+%F %H:%M:%S") | Install Dependencies | END"
 
       - name: Compile TypeScript
-        run: npm run build
+        run: |
+          echo "$(date "+%F %H:%M:%S") | Compile TypeScript | START"
+          npm run build
+          echo "$(date "+%F %H:%M:%S") | Compile TypeScript | END"
 
       - name: Run Tests
-        run: npm test
+        run: |
+          echo "$(date "+%F %H:%M:%S") | Run Tests | START"
+          npm test
+          echo "$(date "+%F %H:%M:%S") | Run Tests | END"
